[package]
name = "native_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name ="native_rust"
crate-type = ["cdylib", "staticlib"]

[dependencies]
